import { useCallback, useMemo, useState } from 'react';
import { useFocusEffect, router } from 'expo-router';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { ArrowRight, HeartPulse, ScanLine, ShieldCheck, MessageCircleHeart, Pill, ChartNoAxesCombined, MapPin } from 'lucide-react-native';
import { Colors } from '@/constants/theme';
import { readingLabel } from '../health/HealthHistory';
import { todayOccurrences } from '../medications/occurrences';
import { loadHomeData } from './home-data';
import { ActivityFeedback } from '@/components/activity-feedback';

export default function HomeScreen() {
  const c = Colors[useColorScheme() === 'dark' ? 'dark' : 'light'];
  const styles = useMemo(() => makeStyles(c), [c]);
  const [data, setData] = useState<Awaited<ReturnType<typeof loadHomeData>>>();
  const [refreshing, setRefreshing] = useState(false);
  const [refresh, setRefresh] = useState(0);
  const [now, setNow] = useState(new Date());
  useFocusEffect(useCallback(() => {
    let active = true;
    setRefreshing(true);
    void loadHomeData().then(result => { if (active) { setData(result); setNow(new Date()); setRefreshing(false); } }).catch(() => { if (active) setRefreshing(false); });
    const timer = setInterval(() => { if (active) setNow(new Date()); }, 60000);
    return () => { active = false; clearInterval(timer); };
    // Manual refresh intentionally reloads the focused screen.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [refresh]));
  const reminders = data?.management ? todayOccurrences(data.management.medicines, data.management.schedules, data.management.intakes, now) : [];
  const taken = reminders.filter(item => item.status === 'taken').length;
  const activeMedicines = data?.management?.medicines.filter(item => item.is_active).length;
  const weeklyReadings = data?.summary ? Object.entries(data.summary.counts).filter(([key]) => key !== 'total').reduce((sum, [,count]) => sum + (typeof count === 'number' ? count : 0), 0) : undefined;
  const greeting = now.getHours() < 12 ? 'Good morning' : now.getHours() < 18 ? 'Good afternoon' : 'Good evening';
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => setRefresh(value => value + 1)} tintColor={c.primary} />}>
    <View style={styles.hero}><Text style={styles.date}>{now.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</Text><Text style={styles.title}>{greeting}. Kumusta?</Text><Text style={styles.body}>Let’s make today a little easier. Check a reminder, log a reading, or ask Alalay for a hand.</Text><View style={styles.trust}><ShieldCheck size={18} color={c.primary}/><Text style={styles.trustText}>Works offline • Data stays on this device</Text></View></View>
    {!data && <ActivityFeedback label="Putting your day together…"/>}
    {data && <View style={styles.actions}>{[{ value: activeMedicines, label: 'Active medicines', route: '/medications' }, { value: data.medicineError ? undefined : reminders.length, label: 'Reminders today', route: '/medications' }, { value: weeklyReadings, label: 'Readings in 7 days', route: '/insights' }].map(item => <Pressable accessibilityRole="button" key={item.label} onPress={() => router.push(item.route as '/medications' | '/insights')} style={[styles.card, { flex: 1, minWidth: 95 }]}><Text style={[styles.time, { fontSize: 28 }]}>{item.value ?? '—'}</Text><Text style={styles.caption}>{item.label}</Text></Pressable>)}</View>}
    <Text style={styles.subtitle}>What can we do today?</Text>
    <View style={styles.actions}><Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/health', params: { add: '1' } })} style={styles.primary}><HeartPulse size={22} color={c.onPrimary}/><Text style={styles.primaryText}>Log a reading</Text></Pressable><Pressable accessibilityRole="button" onPress={() => router.push('/scan')} style={styles.secondary}><ScanLine size={22} color={c.primary}/><Text style={styles.secondaryText}>Scan prescription</Text></Pressable></View>
    <View style={styles.sectionHeader}><Text style={styles.subtitle}>Today’s reminders</Text><Pressable accessibilityRole="button" accessibilityLabel="Manage medicines and reminders" onPress={() => router.push('/medications')} style={styles.linkButton}><Text style={styles.link}>Manage</Text><ArrowRight size={18} color={c.primary}/></Pressable></View>
    {data?.medicineError ? <View style={styles.card}><Text style={styles.body}>Your reminders couldn’t be loaded. Your existing records have not been changed.</Text><Pressable accessibilityRole="button" onPress={() => setRefresh(value => value + 1)} style={styles.linkButton}><Text style={styles.link}>Try again</Text></Pressable></View> : reminders.length ? <View style={styles.card}><Text style={styles.caption}>{taken} of {reminders.length} recorded as taken today</Text>{reminders.slice(0, 4).map(item => <Pressable accessibilityRole="button" accessibilityLabel={`Manage reminder for ${item.name} at ${item.time_local}`} key={item.schedule_id} onPress={() => router.push('/medications')} style={styles.reminder}><View style={styles.reminderTime}><Text style={styles.time}>{item.time_local}</Text><Pill size={18} color={c.primary}/></View><View style={styles.flex}><Text style={styles.name}>{item.name}</Text><Text style={styles.caption}>{item.status === 'not_recorded' ? 'Due time passed · Not recorded' : item.status === 'upcoming' ? 'Upcoming' : item.status === 'taken' ? 'Taken' : 'Skipped'}</Text></View><ArrowRight size={18} color={c.textMuted}/></Pressable>)}{reminders.length > 4 && <Text style={styles.caption}>View all {reminders.length} reminders in Medicines.</Text>}</View> : data && <View style={styles.card}><Text style={styles.name}>{data.management?.medicines.length ? 'No reminders scheduled for today' : 'A gentle reminder starts here'}</Text><Text style={styles.body}>{data.management?.medicines.length ? 'Check your prescribed times in Medicines and manage your reminders.' : 'Add a medicine from your prescription, then choose reminder times that work for you.'}</Text><Pressable accessibilityRole="button" onPress={() => router.push('/medications')} style={styles.linkButton}><Text style={styles.link}>{data.management?.medicines.length ? 'Manage reminders' : 'Add your first medicine'}</Text><ArrowRight size={18} color={c.primary}/></Pressable></View>}
    <View style={styles.sectionHeader}><Text style={styles.subtitle}>Recent readings</Text><Pressable accessibilityRole="button" onPress={() => router.push('/insights')} style={styles.linkButton}><Text style={styles.link}>See trends</Text><ArrowRight size={18} color={c.primary}/></Pressable></View>
    <View style={styles.card}>{data?.readingError ? <Text style={styles.body}>Your saved readings couldn’t be loaded. Pull down to try again.</Text> : data?.readings.length ? data.readings.slice(0, 3).map(reading => <View style={styles.reading} key={reading.id}><Text style={styles.name}>{readingLabel(reading)}</Text><Text style={styles.caption}>{new Date(reading.recorded_at).toLocaleString()}</Text></View>) : <><Text style={styles.name}>Your health story starts with one reading</Text><Text style={styles.body}>Record blood pressure, glucose, temperature, weight or a symptom. Your saved history will appear here.</Text></>}</View>
    <Pressable accessibilityRole="button" onPress={() => router.push('/assistant')} style={styles.assistant}><MessageCircleHeart color={c.primary} size={32}/><View style={styles.flex}><Text style={styles.name}>A little alalay, whenever you need it</Text><Text style={styles.body}>Ask about your records or get help logging a reading.</Text></View><ArrowRight color={c.primary} size={20}/></Pressable>
    <View style={styles.card}><Text style={styles.name}>Try asking Alalay</Text>{['What reminders do I have today?', 'Show my recent readings', 'Remember that I prefer short replies'].map(suggestion => <Pressable key={suggestion} accessibilityRole="button" onPress={() => router.push({ pathname: '/assistant', params: { suggestion } })} style={styles.linkButton}><Text style={[styles.link, { flex: 1 }]}>{suggestion}</Text><ArrowRight size={18} color={c.primary}/></Pressable>)}</View>
    <View style={styles.actions}><Pressable accessibilityRole="button" onPress={() => router.push('/insights')} style={styles.secondary}><ChartNoAxesCombined size={22} color={c.primary}/><Text style={styles.secondaryText}>Health insights</Text></Pressable><Pressable accessibilityRole="button" onPress={() => router.push('/directory')} style={styles.secondary}><MapPin size={22} color={c.primary}/><Text style={styles.secondaryText}>Find nearby care</Text></Pressable></View>
    <Text style={styles.caption}>For missed-dose or food advice, check the exact medicine leaflet or ask a pharmacist. Paalalay does not prescribe or change doses.</Text>
  </ScrollView>;
}
function makeStyles(c: typeof Colors.light | typeof Colors.dark) { return StyleSheet.create({ screen: { flex: 1, backgroundColor: c.background }, content: { padding: 20, paddingBottom: 36, gap: 16, maxWidth: 900, width: '100%', alignSelf: 'center' }, hero: { gap: 12, paddingVertical: 12 }, title: { fontFamily: 'Manrope_700Bold', color: c.text, fontSize: 28, lineHeight: 36 }, date: { fontFamily: 'Manrope_600SemiBold', color: c.textMuted, fontSize: 14 }, body: { fontFamily: 'Manrope_400Regular', color: c.textMuted, fontSize: 15, lineHeight: 23 }, trust: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: c.surfaceVariant, padding: 12, borderRadius: 12 }, trustText: { color: c.primary, fontSize: 13, flexShrink: 1 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, primary: { flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: c.primary, padding: 16, minHeight: 52, borderRadius: 16, flexGrow: 1 }, primaryText: { color: c.onPrimary, fontFamily: 'Manrope_600SemiBold', fontSize: 15 }, secondary: { flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: c.surfaceVariant, padding: 16, minHeight: 52, borderRadius: 16, flexGrow: 1 }, secondaryText: { color: c.primary, fontFamily: 'Manrope_600SemiBold', fontSize: 15 }, sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, subtitle: { color: c.text, fontFamily: 'Manrope_700Bold', fontSize: 20, flexShrink: 1 }, linkButton: { minHeight: 48, flexDirection: 'row', gap: 8, alignItems: 'center' }, link: { color: c.primary, fontFamily: 'Manrope_600SemiBold', fontSize: 15 }, card: { padding: 16, borderRadius: 20, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, gap: 12 }, name: { color: c.text, fontFamily: 'Manrope_600SemiBold', fontSize: 16, lineHeight: 24 }, caption: { color: c.textMuted, fontFamily: 'Manrope_400Regular', fontSize: 13, lineHeight: 20 }, reminder: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 64, paddingVertical: 8 }, reminderTime: { gap: 4, alignItems: 'center' }, time: { color: c.primary, fontFamily: 'Manrope_700Bold', fontSize: 18, fontVariant: ['tabular-nums'] }, flex: { flex: 1 }, reading: { paddingVertical: 8, gap: 4 }, assistant: { flexDirection: 'row', gap: 12, alignItems: 'center', padding: 20, backgroundColor: c.surfaceVariant, borderRadius: 20 } }); }
